use bzlmod instead of go.mod deps to workaround:
ERROR: error loading package '@@gazelle~~go_deps~com_github_jbedard_go_workspaces_bzlmod_a//': Unable to find package for @@[unknown repo 'rules_go' requested from @@gazelle~~go_deps~com_github_jbedard_go_workspaces_bzlmod_a (did you mean 'rules_cc'?)]//go:def.bzl: The repository '@@[unknown repo 'rules_go' requested from @@gazelle~~go_deps~com_github_jbedard_go_workspaces_bzlmod_a (did you mean 'rules_cc'?)]' could not be resolved: No repository visible as '@rules_go' from repository '@@gazelle~~go_deps~com_github_jbedard_go_workspaces_bzlmod_a'.